exp_name: modelnet

model: GTINet
dataset: modelnet40
model_path: 
dim: 8 #unseen和same为8，其他为16 
# -------------------------modelenet40-------------------
rot_factor: 4 
gaussian_noise: False # add noise
unseen: True # True for unseen / False for the same

# -------------------------icl_nuim----------------------
max_angle: 45
max_trans: 0.5
data_file_test: ./data/test/icl_nuim.h5
data_file: ./data/train/icl_nuim.h5

# -------------------------7scenes-----------------------
mode: train
mag: 1
workers: 4
dataset-path: ./data/7scene
categoryfile: ./data/categories/7scene_train.txt

# --------------------------kitti-------------------------
voxel_size: 0.3
root: ./data/kitti_dataset/sequences/
data_list: ./data/kitti_list
augment: 1.0


# ------------ ----model hyper parameters------------------
nhead: 4 #4
nn_margin: 0.7
partial: [1, 1]
loss_margin: 0.01
list_k1: [10,10] #10 for same+unseen 32for noise
list_k2: [10,10]
emb_dims: 256
n_iters: 2 #noise时为1 ，其他为2
n_points: 1024
n_subsampled_points: 768 #75%
batch_size: 8 #4
test_batch_size: 8
epochs: 50
use_sgd: False
n_keypoints: 256 
lr: 0.001 # 0.001 for noise+unseen / 0.001 for same
momentum: 0.9
no_cuda: False
seed: 1234
start_epoch: 0
lr_step: [25,50,75,100]

# ------------------network training-----------------------
resume: False

# ------------------network testing------------------------
eval: True # True for testing / False for training
